### ISSUE TITLE
ERROR ABORT_HALT when using halt/0

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#1]
When running following code using `tpl`, it failed to return to the shell.

```
:- initialization(main).

main :- write('Hello, world!'), nl, halt.
```

REPL status is like following:

```
% ./tpl foo.pl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 20 2016
Hello, world!
ERROR: ERROR ABORT_HALT
?-
```

**Comment by trealla-lang** [comment]
Fixed. Well, was crashing for me due to a print error. Now halts and exit program.
