### ISSUE TITLE
get_char/1 and get_code/1 consume whole line buffer instead a single character?

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#10]
See following code:

```
get_delimited(D, S) :-
    get_char(C),
    (C = D -> S = []; get_delimited(D, S1), S = [C|S1]).

main :- get_delimited('\n', S), write(S), halt.
```

In gprolog and swi, I can use `get_delimited/2` to read a line, but in Trealla `get_char/1` seems to consume whole line in a single call.

**Comment by infradig** [comment]
Oops, code for debugging was left in. FIXED.
