### ISSUE TITLE
Missing choice points

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#104]
For following code, some choice ponts are missing:

```
:- initialization(main).

foo([bar(a), bar(b), bar(c), bar(d)]).

main :- foo(Bars), member(bar(Bar), Bars), write(Bar), nl, fail.
main :- halt.
```

Output:

```
Trealla v0.1alpha, Mar  1 2017
INFO: consulted 'foo.pl': 64 terms
a
b
Halted
```

**Comment by infradig** [comment]
Interesting, because:

:- initialization(main).

foo([a, b, c, d]).

main :- foo(Bars), member(Bar, Bars), write(Bar), nl, fail.
main :- halt.

clearly works.

**Comment by infradig** [comment]
I have reduced it to this:

:- initialization(main).
main :- member(X, [a,b,c,d]), var(Bar), writeln(X), Bar=X, fail.
main :- halt.
a
b
Halted

The choicepoints are there, it seems Bar is not reset on bactracking after the first two times, so Var(Bar) is eventually failing.

**Comment by infradig** [comment]
:- initialization(main).
main :- member(X, [a,b,c,d]), writeln(X),var(Bar), Bar=X,writeln(Bar),fail.
main :- halt.
a
a
b
b
c
d
Halted

So Bar is not being rest on backtracking.

**Comment by dram** [comment]
Cool! Fix confirmed, thanks.
