### ISSUE TITLE
number_chars/2 failed for recursively constructed list of characters

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#11]
This bug is quite strange, `number_chars/2` can convert literal list of characters, but failed for recursively constructed one, e.g.:

```
get_delimited(D, S) :-
    get_char(C),
    (C = D -> S = []; get_delimited(D, S1), S = [C|S1]).

main :-
    get_delimited('\n', S),
    number_chars(N, S),
    write(N), nl, halt.
```

Session record:

```
% ./trealla/tpl foo.pl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 22 2016
1
ERROR: ERROR ABORT_INVALIDARGNOTINT
```

**Comment by infradig** [comment]
It's picked up the '\n' for some reason.

**Comment by dram** [comment]
Also I failed to get length of `S` by `length(S, Len)`.

**Comment by infradig** [comment]
Yeah, the list is lost at that point.

**Comment by infradig** [comment]
Hopefully fixed. My head is spinning.

**Comment by dram** [comment]
Cool! Fix confirmed.
