### ISSUE TITLE
Multiline comment support

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#113]
For following code, GProlog, SWI and YAP runs successfully:

```
/*
        foo1
        foo2
*/

:- initialization(main).

main :-
        write(hi /* bar1 */), nl, /* bar2 */ halt. /* bar3 */
```

Trealla will failed with following error:

```
% tpl foo.pro
ERROR: unknown operator: '/*'
ERROR: consult 'foo.pro', line=1, '/*'
```

According to [SWI-Prolog manual](http://www.swi-prolog.org/pldoc/man?section=isosyntax#sec:2.16.1.2), multiline comment is specified in ISO Prolog, so it would be nice if Trealla can support that.

**Comment by infradig** [comment]
Ok, didn't know that!

**Comment by dram** [comment]
Trailing whitespace after `*/` will cause parsing error, I have updated test case in trealla-tests.

Reopen this issue.

**Comment by dram** [comment]
Thanks!

**Comment by dram** [comment]
Still has problem for following code:

```
:- initialization(main).

main :-
        A = foo, /*foo*/
        write(A), nl, halt.
```

I have add this code to trealla-tests.

Reopen this issue.

**Comment by dram** [comment]
Add another test in trealla-tests repo:

```
/*
************************************/

/*
foo bar foo bar foooooooooo bar 
************************************/

```

**Comment by dram** [comment]
Fix confirmed, thanks!
