### ISSUE TITLE
Missing ISO predicate current_prolog_flag/2

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#115]
According to documents of [GProlog](http://gprolog.org/manual/gprolog.html#current-prolog-flag/2) and [SWI Prolog](http://www.swi-prolog.org/pldoc/doc_for?object=current_prolog_flag/2), `current_prolog_flag/2` is an ISO predicate which can be used to fetch info about current flags.

**Comment by infradig** [comment]
It was victim of a search/replace gone too far.

I haven't looked up what the actual ISO flags are, if any. Trealla
implements a few of them.

**Comment by dram** [comment]
Thanks.

No sure if there are any flags specified by ISO Prolog, can not find any refereneces.

**Comment by dram** [comment]
Document of GProlog have a table about supported  prolog flags, with last column shows if that flags are specified by ISO or not.

http://gprolog.org/manual/gprolog.html#set-prolog-flag%2F2
