### ISSUE TITLE
Use operator symbols as atoms

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#116]
It seems that in Trealla undefined operator symbols can not be used as atoms.

For following code, GProlog, SWI and YAP all output `+-?`, but Trealla will failed to run.

```
:- initialization(main).

main :-
    foo(+, -, ?) = foo(X, Y, Z),
    write(X), write(Y), write(Z), nl, halt.
```

Error output for Trealla:

```
% tpl foo.pl
ERROR: unknown operator: '?'
ERROR: consult 'foo.pl', line=4, '    foo(+, -, ?) = foo(X, Y, Z),'
```

**Comment by dram** [comment]
In GProlog, SWI and YAP, it seems that all unknown operators can be used as atoms, not only known ones. So I think only define `?` as operator is not enough.

Reopen it.

**Comment by infradig** [comment]
Ok, seems you are right.

**Comment by dram** [comment]
Fix confimed, thanks!
