### ISSUE TITLE
Negation in `is/2` expression

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#117]
Following code will cause error in Trealla:

```
:- initialization(main).

main :- N = 1, N1 is -N, write(N1), nl, halt.
```

Output:

```
% tpl foo.pl 
ERROR: syntax error, excess terms
ERROR: consult 'foo.pl', line=3, 'main :- N = 1, N1 is -N, write(N1), nl, halt.'
```

It runs ok in GProlog, SWI and Yap.

**Comment by infradig** [comment]
I've just been looking at that, stumbled upon it yesterday.

**Comment by dram** [comment]
Cool!

With this fix, Trealla can now parse [?-Prolog](https://bitbucket.org/bunny351/prolog) bootstrap compiler successfully.

**Comment by infradig** [comment]
Excellent. Meaning to have a look at that in detail.

**Comment by infradig** [comment]
I found another negation bug and fixed that. Also updated the issue-test.

?-Prolog looks interesting.

**Comment by dram** [comment]
Yes, it would be interesting if Trealla can be used to bootsrap ?-Prolog, can be treated as a non-trivial test for Trealla.

**Comment by infradig** [comment]
I can only get swipl to work with that 'pc' script, and then by adding
--traditional.

**Comment by dram** [comment]
Yes, I think it only works with SWI-Prolog 6.
