### ISSUE TITLE
ABORT_TYPEERROR for float/1

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#12]
Following code cause `ABORT_TYPEERROR` error in Trealla:

```
main :- N is float(1), write(N), nl, halt.
```

**Comment by infradig** [comment]
Seems function integer/1 isn't even ISO. Yap includes it but treats it as an integer 'cast'. SWI treats it as a synonym for round/1. GProlog doesn't include it. I'm going with Yap I think.

**Comment by dram** [comment]
For "cast" do you mean truncate? According to Yap's [document](https://www.dcc.fc.up.pt/~vsc/Yap/documentation.html#Arithmetic), its `integer/1` is similar to `truncate/1`, except that it also accept integer as argument.

BTW, following code cause a segmentation fault:

```
X is integer(-1.2).
```

**Comment by infradig** [comment]
Yes, truncate.
