### ISSUE TITLE
Old-style IO predicates

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#129]
Although non-ISO, GProlog, SWI and Yap all support old-style IO predidates, e.g. `see/1`, `seen/0`, `tell/1`, `told/0`, ?-Prolog also make heavy use of it.

It would be nice if Trealla can also support this.

Following are some links:

http://gprolog.org/manual/gprolog.html#sec181
http://www.swi-prolog.org/pldoc/man?section=edinburghIO
https://www.dcc.fc.up.pt/~vsc/Yap/documentation.html#Handling-Streams-and-Files

**Comment by dram** [comment]
Sorry, I missed `set_input/1` and `set_output/1`, so those old style predicates are not necessary, close this issue.

**Comment by infradig** [comment]
I am adding them anyway. Always intended too.
