### ISSUE TITLE
Precedence of `,` and `;`?

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#13]
For following code, GProlog, SWI and Yap all print out `foo` and drop into REPL, only Trealla print out `foobar` and halted.

```
main :- A = 1, write('foo'); B = 2, write('bar'), halt.
```

The trace output is:

```
% ./tpl --trace ../foo.pl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 25 2016
Call: ?- main
Exit: ?-
Call: main
Exit: main
Call: A=1
Exit: 1=1
Call: (write('foo') ; 
                B=2)
fooExit: write('foo')
Call: !
Exit: !
Call: write('bar')
barExit: write('bar')
Call: halt
Fail: halt
```

**Comment by infradig** [comment]
It was a source-level optimization that makes things about 25% faster. I have disabled it. If you need speed add -nocanonical to command-line options and make sure you use parentheses with disjunction:

    main :- (A = 1, write('foo')); (B = 2, write('bar')), halt.

I'll try and find a better solution in time.

**Comment by infradig** [comment]
But for now it works as it should, just slower.

**Comment by infradig** [comment]
Except now queens8 doesn't work.

**Comment by infradig** [comment]
Well, queens8 actually generates all the solutions, it just doesn't terminate the search for some reason.

**Comment by infradig** [comment]
Ok, was creating an unnecessary choice point doing conjunction. Now works properly and is faster.

**Comment by dram** [comment]
Cool!

Also learned a new tool, `--listing`, which is more suitable for investigating those kind problems.

Thanks.

**Comment by infradig** [comment]
Also added --listing_canonical

**Comment by dram** [comment]
Yeah, I see.

BTW, I find that Trealla can not list code with `initialization/1` specified, e.g.:

```
:- initialization(main).

main :- write(hi), nl, halt.
```

**Comment by infradig** [comment]
True

**Comment by dram** [comment]
I think this issue is back, maybe already a long time. I did not track it properly.

I'll reopen this.

**Comment by infradig** [comment]
I'm going to back the merge out, I will think about this more when things are quieter.

**Comment by dram** [comment]
OK, reasonable.

**Comment by infradig** [comment]
Ok, i'm reinstating your FLAG_BARE change, even though this breaks queens8 etc. It's more correct and necessary for operator precedence parsing. It does make things run slower (about 50% slower) as all those conjunctions now have to be processed, but I will write a routine to scan and lift them up and inline them.

A fix for what ails queens8 will have to wait.
