### ISSUE TITLE
Atoms containing `\0`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#133]
It is interesting that GProlog, SWI and Yap behaves differently when creating atoms containing `\0'.

GProlog will report an error:

```
% gprolog
| ?- atom_codes(A, [0x61, 0, 0x61]).
uncaught exception: error(representation_error(character_code),atom_codes/2)
| ?-
```

SWI will create an atom successfully:

```
% swipl
1 ?- atom_codes(A, [0x61, 0, 0x61]).
A = 'a\000\a'.

2 ?-
```

Yap will create an atom truncated:

```
% yap
   ?-  atom_codes(A, [0x61, 0, 0x61]).
A = a
   ?-
```

I kind of think that both GProlog and SWI's behaviour is acceptable, currently Trealla behaves like Yap.

**Comment by infradig** [comment]
Yes, I don't think '\0' should be accpetable so favour the GProlog approach.

**Comment by dram** [comment]
Fix confirmed, thanks.
