### ISSUE TITLE
Strange bug related to predicate arity

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#136]
Following code is simplified from `'$rdtok_read_string'` in [`rdtok.pl`](https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/lib/rdtok.pl) included in ?-Prolog, which is used to read quoted tokens.

```
:- initialization(main).

main :-
        see('foo.txt'),
        get_code(39),
        read_quoted(Chars),
        write(Chars), nl, halt.

read_quoted(Chars) :-
        get_code(C),
        read_quoted(C, Chars).

read_quoted(39, Chars) :- !,
        Chars = [].
read_quoted(Char, [Char|Chars]) :-
        read_quoted(Chars).
```

It does not work properly in Trealla. But if I rename `read_quoted/2` to `read_quoted_helper/2`, so name `read_quoted` is only used by `read_quoted/1`, then it will run correctly.

I'll add a full test case to trealla-tests repo.

**Comment by dram** [comment]
BTW, this test do not terminate directly even after renaming that predicate, but waiting for user input, maybe a seperate issue.

**Comment by infradig** [comment]
This is related to #135 and am still working on this area.

**Comment by infradig** [comment]
Worked with -O2, seems tail recursion elimination wasn't checking arity.

**Comment by dram** [comment]
I think this issue can be closed now.
