### ISSUE TITLE
Missing ISO predicate current_op/3 and current_predicate/1

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#138]
ISO predicate `current_op/3` and `current_predicate/1` is missing in Trealla.

Some links:

http://www.swi-prolog.org/pldoc/doc_for?object=current_op/3
http://gprolog.org/manual/gprolog.html#sec171
https://www.dcc.fc.up.pt/~vsc/Yap/documentation.html#Misc

http://www.swi-prolog.org/pldoc/doc_for?object=current_predicate/1
http://gprolog.org/manual/gprolog.html#current-predicate%2F1
https://www.dcc.fc.up.pt/~vsc/Yap/documentation.html#Looking-at-the-Database

**Comment by infradig** [comment]
Ok, current_predicate/1 done, current_op/3  partially implemented (it doesn't backtrack).

**Comment by dram** [comment]
Sorry, but it seems that is not enough for bootstraping ?-Prolog, e.g.:

```
% tpl
Trealla v0.1alpha, Jun  7 2017
?- current_op(N, fx, ':-').
false.
?-
```

Which should be `1200`.

**Comment by infradig** [comment]
Should be ok.

**Comment by dram** [comment]
Confirmed, thanks!
