### ISSUE TITLE
REPL quit immediately after error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#139]
With recent changes, REPL will quit immediately after error:

```
% tpl
Trealla v0.1alpha, Jun  7 2017
?- foo.
ERROR: UNKNOWN -> 'foo/0'
Halted
%
```

**Comment by infradig** [comment]
There seems to be a problem with the 0052 test. The exit status is 0 but
the test complains it isn't?

**Comment by infradig** [comment]
Nevermind! I see the problem.

**Comment by dram** [comment]
Can be closed now, thanks.
