### ISSUE TITLE
Missing predefined streams

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#140]
According [document](http://gprolog.org/manual/gprolog.html#sec116) of GProlog, there are three predefined standard streams:  user_input, user_output, user_error, not sure if it is defined by ISO.

e.g. following code works on GProlog, SWI and Yap.

```
:- initialization(main).

main :- write(user_output, foo), nl, halt.
```

**Comment by infradig** [comment]
I doubt it's ISO, they use stdin/stdout as names. But I will add it in.

**Comment by dram** [comment]
Cool! Thanks.
