### ISSUE TITLE
Unification error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#150]
Following code is simplified from `read_symbol/3` in [?-Prolog](https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/lib/rdtok.pl):

```
:- initialization(main).

foo(a, [a|L]) :- foo(b, L).
foo(b, []).

main :- foo(a, L), write(L), nl, halt.
```

Output:

```
% tpl foo.pro
[a|L]
```

Should be `[a]`.

**Comment by infradig** [comment]
Seems to be a printing error, as the test L=[a] succeeds after the call to
foo.

**Comment by infradig** [comment]
Actually, it's to do with -O3 optimization again, as -O2 works. Seems a
frame has been clobbered.

**Comment by dram** [comment]
It seems to be a regression of recent changes. As those line s of code in ?-Prolog works well previously.

**Comment by infradig** [comment]
Also putting the foo(b,[]) line first works too, case of premature TCO it
seems.

**Comment by dram** [comment]
Fix confirmed, thanks.
