### ISSUE TITLE
Another unification error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#151]
Following code is simplified from [read_tokens/3](https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/lib/rdtok.pl) in ?-Prolog:

```
:- initialization(main).

foo(-1, A) :- write(A).
foo(1, A) :- write(A), foo(-1, b).
foo(_, _).

main :- foo(1, a), nl, halt.
```

The result should be `ab`, but Trealla outputs `a`.

**Comment by infradig** [comment]
Seems negative numbers have disappeared:

?- listing.
foo(1,A) :-
write(A).
foo(1,A) :-
write(A),
foo(1,b).
foo(_,_).
main :-
foo(1,a),
nl,
halt.
true.

**Comment by dram** [comment]
Although result is correct now, but listing output is still not quite right:

```
?- listing.
foo(1,A) :-
        write(A),
        foo(-,1,b).
foo(_,_).
foo(-,1,A) :-
        write(A).
main :-
        foo(1,a),
        nl,
        halt.
true.
?-
```

**Comment by dram** [comment]
BTW, seems that clause orders are not perserved when listing?

**Comment by dram** [comment]
Can be closed now, thanks.
