### ISSUE TITLE
Unification error for `:-`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#154]
Trealla failed to unify following code (simpilifed from `build_index_to_type_map` in https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/index.pl):

```
:- initialization(main).

foo((A :- _)) :- write(A), nl.

main :- foo((bar :- baz)), halt.
```

GProlog, SWI and Yap all output `bar`.

**Comment by infradig** [comment]
Odd, my GProlog (1.4.5) doesn't accept it. If I change to:

:- initialization(main).

foo(A :- _) :- write(A), nl.
main :- foo(bar :- baz), halt.


Trealla & SWI are ok, Yap and GProlog complain.

**Comment by dram** [comment]
Fix confirmed, thanks.

GProlog 1.3.0 also doesn't accept it (without parenthesis).
