### ISSUE TITLE
No PUT or DELETE method for HTTP/1.0

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#164]
According to the [spec](https://www.w3.org/Protocols/HTTP/1.0/spec.html#Methods), `PUT` and `DELETE` method is not defined in HTTP/1.0, so I think `http:del10/4` and `http:put10/6` are not needed.

**Comment by infradig** [comment]
I really have no strong feelings about this. But shouldn't POST support www-form blahblah encoding and set the MIME type accordingly?

**Comment by infradig** [comment]
Yes, I probably agree with this.
