### ISSUE TITLE
Mix use of `findall/3`, `recorded/3` and `erase/1`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#172]
Following code do not work properly in Trealla, which is simplifed from `process_boilerplate_code/1` in [?-Prolog](https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/process.pl#process.pl-231:236):

```
:- initialization(main).

main :-
        recordz(foo, a),
        recordz(foo, b),
        recordz(foo, c),
        findall(A, (recorded(foo, A, Ref), erase(Ref)), Atoms),
        write(Atoms), nl, halt.
```

SWI will output `[a,b,c]`, Trealla only output `[a]`. Also valgrind detect some memory errors.

**Comment by infradig** [comment]
I think erase is losing the position for clause/3, which recorded uses. As
noted, database is currently *immediate-update* view rather than the ISO
*logical* view.

**Comment by dram** [comment]
Fix confirmed, thanks.

**Comment by dram** [comment]
`erase/1` do not truly erase records. I have updated test code in trealla-tests.

**Comment by infradig** [comment]
Problem was moving it into lists library module. Then erase/1 couldn't find
the reference.

**Comment by dram** [comment]
Fix confirmed, thanks.
