### ISSUE TITLE
How to use the new `http:get/3` api?

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#174]
For following code, I can not find way to fetch the contents of response:

```
:- initialization(main).

main :-
        net:client('http://www.example.com', S),
        http:get(S, /, [debug(true)]),
        net:stash_get(S, 'Content-Length', LengthAtom),
        atom_number(LengthAtom, Length),
        sys:bread(S, Length, Response),
        write(Length), nl,
        halt.
```

Output:

```
GET / HTTP/1.1
Host: www.example.com
User-Agent: Trealla
Transfer-Encoding: chunked
Connection: keep-alive
Accept-Encoding: chunked

0
```

**Comment by infradig** [comment]
You always have to call parse/3 now.

**Comment by infradig** [comment]
Also, set the length to 0 I think.

**Comment by infradig** [comment]
For example, from library/http_client.pro

get11_internal(S,Path,Data) :-
http:get(S,Path,[version(1.1),length(0),persist(false)]),
http:parse(S,Status),
Status = 200,
net:stash_get(S,'CONTENT_LENGTH',LenStr,'-1'),
atom_number(LenStr,Len),
(Len >= 0 -> bread(S,Len,Data) ; get11_chunk(S,'',Data)),
true.

**Comment by infradig** [comment]
Also, i'm going to make it an option whether to accept chunked responses.

**Comment by dram** [comment]
It is a bit strange to have to specify `length(0)` explicitly for GET method, I think that should be the default, according to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.1):

> A payload within a GET request message has no defined semantics;
> sending a payload body on a GET request might cause some existing
> implementations to reject the request.

**Comment by infradig** [comment]
ok, had wondered.

**Comment by dram** [comment]
Can be closed now, thanks.
