### ISSUE TITLE
Use `initialization` as a compound term functor

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#186]
Directive `initialization` can not be used as a compound term functor in Trealla, e.g.:

```
:- initialization(main).

foo(initialization(X)) :- write(X), nl.

main :-
        T = initialization(a),
        foo(T),
        halt.
```

Output:

```
% tpl foo.pro
ERROR: syntax error, excess terms
ERROR: consult 'foo.pro', line=8, '     halt.'
```

Which works in GPorlog, SWI and Yap.

**Comment by infradig** [comment]
Ok will look into, but I get this for GProlog:

$ gprolog
GNU Prolog 1.4.5 (64 bits)
Compiled Feb  5 2017, 10:30:08 with gcc
By Daniel Diaz
Copyright (C) 1999-2016 Daniel Diaz
*| ?- ['~/trealla-tests/issues/0186.pro <http://0186.pro>'].*
compiling /home/andrew/trealla-tests/issues/0186.pro for byte code...
/home/andrew/trealla-tests/issues/0186.pro compiled, 8 lines read - 691
bytes written, 13 ms
warning: /home/andrew/trealla-tests/issues/0186.pro:1: user directive
caused exception: error(existence_error(procedure,foo/0),main/0)

yes
*| ?- listing.*
% file: /home/andrew/trealla-tests/issues/0186.pro

foo((initialization A)) :-
write(A),
nl.

main :-
A = (initialization a),
foo(A),
halt.

yes
*| ?- main.*
uncaught exception: error(existence_error(procedure,foo/0),main/0)
*| ?- halt.*
$

**Comment by dram** [comment]
Interesting, it works in GProlog 1.3.0 and 1.4.4.

**Comment by infradig** [comment]
For now I can only fix this by dropping the op=fx definition for
initialization.

**Comment by dram** [comment]
Then `tests/0003-initialization.pl` in ?-Prolog will fail with another error:

```
% ./pc tests/0003-initialization.pl

** atom follows expression
:- initialization <<here>> foo
ERROR: UNKNOWN -> 'throw/1'
```

**Comment by dram** [comment]
Thanks, fix confirmed.
