### ISSUE TITLE
Syntax error for xor/2

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#187]
Following code will cause syntax error:

```
:- initialization(main).

main :- N is xor(0, 1), write(N), nl, halt.
```

Output:

```
% tpl foo.pro
ERROR: syntax error, excess terms
ERROR: consult 'foo.pro', line=3, 'main :- N is xor(0, 1), write(N), nl, halt.'
```

Which works on GProlog, SWI and Yap.

**Comment by infradig** [comment]
This is the same problem as initialization/1, Trealla can't handle
something being an op as as well as compound form. At the moment I don't
have a solution for this as I can't figure out how to get the parser as it
is to disambiguate.

**Comment by infradig** [comment]
Fix. A very hacky fix for this operator stuff.

**Comment by infradig** [comment]
Damn, the infix is not working.

**Comment by infradig** [comment]
Currently this is ok in Trealla:

  X is 1 xor xor(0, 1).  (SWIPL ok)


but not:

  X is 1 xor (1 xor 0).   (SWIPL ok)

so more required.

**Comment by infradig** [comment]
Currently this is ok in Trealla:

  X is 1 xor xor(0, 1).  (SWIPL ok)

but not:

  X is 1 xor (1 xor 0).   (SWIPL ok)

so more required.

**Comment by dram** [comment]
Thanks, fix confirmed.
