### ISSUE TITLE
Get multiple query values using `http:query/3`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#189]
Currently `http:query/3` only support getting a single value for specified name, if implementing a API server similar to [OpenStack Neutron](https://wiki.openstack.org/wiki/Neutron/APIv2-specification#Filtering_and_Column_Selection), e.g.:

```
GET /v2.0/networks.json?fields=id&fields=name
```

There is no way to get both value of `fields` (`id` and `name`).

It would be nice to make `http:query/3` support backtracking.

Also, currently there is no way to iterate all query name and values, can `http:query/3` be used like this?

```
http:query(S, K, V),
write(K), write(V), nl,
fail
```

**Comment by infradig** [comment]
Sure, will do.

**Comment by infradig** [comment]
Would it be more useful to return a list of values for a key?

**Comment by dram** [comment]
I kind of prefer backtracking, if we return a list, `http:query/3` will be inconvenient if only one value is needed.

**Comment by infradig** [comment]
I am adding

  http:query_list/3

to return a list (or [] if no value). The old call http:query/3 still
returns an atom.

**Comment by dram** [comment]
Nice!

BTW, I found that the result list is in reversed order.

**Comment by dram** [comment]
It works now, thanks!
