### ISSUE TITLE
Missing multifile/1

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#195]
According to document of [GProlog](http://gprolog.org/manual/gprolog.html#sec53), `multifile/1` is specified by ISO.

P.S. I'm trying to run [this Prolog test suite](http://www.deransart.fr/prolog/suites.html), which seems to be useful.

**Comment by infradig** [comment]
Predicates should be multifile already, so the directive would be ignored.
Modules probably can't be yet.

Also, all predicates are discontiguous, so this directive can also be
ignored.

**Comment by dram** [comment]
OK, closing this issue.
