### ISSUE TITLE
Math functions outside of is/2

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#197]
It seems that in Trealla math functions have effect outside of is/2, e.g.:

```
:- initialization(main).

log(S) :- write(S), nl.

main :- log(foo), halt.
```

Trealla output:

```
% tpl --trace foo.pro
Call: ?-main
Call: main
Exit: main
Call: log(foo)
ERROR: ERROR ABORT_TYPEERROR
```

It runs on GProlog, SWI and Yap.

**Comment by infradig** [comment]
Yes, I did this so the REPL could be interactive:

?- log(10).
 2.30258509299405
true.

But this is part of the bigger namespace issue. Probably search local names
first, then builtins.

**Comment by dram** [comment]
Fix confirmed, thanks.
