### ISSUE TITLE
Segmentation fault when evaling single dot

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#2]
Trealla will exit with segmentation fault if entering a `.` and return, e.g.:

```
% ./tpl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 20 2016
?- .
Segmentation fault
```

**Comment by trealla-lang** [comment]
Fixed.

**Comment by dram** [comment]
Following shell script will cause infinite loop:

```
tpl <<EOF
.
EOF
```

I'll reopen this issue.

**Comment by dram** [comment]
Fix confirmed, I'll close this issue.
