### ISSUE TITLE
CYCLIC TERM for `=..`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#204]
Following code will cause CYCLIC TERM for `=..`:

```
:- initialization(main).

bar(X) :- X = [T].

main :-
        bar(L),
        T =.. [foo, A| L],
        write(T), nl,
        halt.
```

**Comment by infradig** [comment]
This is working, but still needs more work. Notably causing problems with
?-Prolog. It might seem a step back but it is needed to fix a fundamental
problem.

**Comment by dram** [comment]
Cool! 👍 

I think this issue can be closed now.
