### ISSUE TITLE
Cut and disjunction

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#211]
Trealla failed for ?-Prolog 0012-cut+disjunction.pl, I tweak the test a bit:

```
:- initialization(main).

main :- (
                foo
        ;
                write(b), nl
        ),
        halt.

foo :-
        (
                !, fail
        ;
                write(a), nl
        ).
```

Should output `b`, instead of `a`.

**Comment by dram** [comment]
According to [document](http://www.swi-prolog.org/pldoc/doc_for?object=!/0) of SWI-Prolog, `;/2` and right hand side of `->/2` should be transparent to the cut.

**Comment by dram** [comment]
Add two more tests to trealla-tests, which related to `->/2`.

**Comment by infradig** [comment]
I know what the problem is with this, just need a good chunk of time to
work on it.

**Comment by dram** [comment]
Cool!

failed test of `tests/0062-recorddb.pl` seems not related to this issue, need more investigation.
