### ISSUE TITLE
Another parsing error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#213]
Following code will cause parsing error in Trealla, found by running ?-Prolog tests/0046-arithmetic.pl.

```
:- initialization(main).

main :-
        write(a), nl,
        \ 0 =:= -1,
        write(b), nl,
        halt.
```

**Comment by infradig** [comment]
Wow, I didn't know about this operator!

**Comment by dram** [comment]
Also surprised. 😄  Fix confirmed.
