### ISSUE TITLE
Unable to construct list using traditional cons notation

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#22]
I find that it is unable to construct list using traditional cons notation in Trealla, although `--traditional` option is supplied and enabled by default. e.g.:

```
% ./tpl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 29 2016
?- A = .(a,[]).
Killed
```

BTW, `[|]` SWI-7 style seems to be always enabled, even in `--traditional` mode, e,g.:

```
% ./tpl --traditional
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 29 2016
?- A = [a|[]].
A: [a] 
(0.000 s) yes
?- 
```

**Comment by infradig** [comment]
I Have removed the SWI-7 stuff, was only playing around with it a while back, and it's not something I want to support.
