### ISSUE TITLE
non-existent file error for phrase/2

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#225]
Following code will cause `non-existent file` error:

```
:- initialization(main).

foo --> [a].

bar --> [b], foo.

main :- phrase(bar, X), write(X), nl, halt.
```

Output:

```
% tpl foo.pro
ERROR: non-existent file 'b'
Trealla v0.1alpha, Jul 16 2017
?-
```

**Comment by dram** [comment]
Fix confirmed.

But still failed for first example of this DCG tutorial: https://www.metalevel.at/prolog/dcg

Need more investigation.

**Comment by infradig** [comment]
Yes, DCG is very rough at this stage.
