### ISSUE TITLE
Variable and `=../2`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#229]
A tricky bug related to `=../2` and variable (which discovered by `tests/0064-findall.pl`), e.g.:

```
:- initialization(main).

main :-
        X = A / B,
        T =.. [foo, C, bar],
        X =.. [/, T, C],
        halt.
```

Tracing output:

```
% tpl --trace foo.pro
Call: ?-main
Call: main
Exit: main
Call: (_1=(_2/_3))
Exit: ((_2/_3)=(_2/_3))
Call: (_4=..[foo,_5,bar])
Exit: (foo(_5, bar)=..[foo,_5,bar])
Call: ((_2/_3)=..[/,foo(_5, bar),_5])
Exit: ((foo(_5, bar)/_3)=..[/,foo(_5, bar),_3])
Call: halt
```

I think that final result should be `(foo(_3, bar)/_3)` instead of `(foo(_5, bar)/_3)`.

**Comment by infradig** [comment]
But, I think _5 is bound to _3. I could change the printing to show that.

**Comment by dram** [comment]
I think this is not a printing problem, for following code:

```
:- initialization(main).

main :-
        X = A / B,
        T =.. [foo, C, bar],
        X =.. [/, T, C],
        foo(D, _) = A,
        D == C,
        write(ok), nl,
        halt.
```

Trealla does not output `ok`, while GProlog, SWI and Yap do.

**Comment by dram** [comment]
Still have problem if those varibles are added to record system, e.g. following code behaviour differently in SWI and Trealla:

```
:- initialization(main).

main :-
        X = A / B,
        T =.. [foo, C, bar],
        X =.. [/, T, C],
        foo(D, _) = A,
        recordz(foo, D / C),
        recorded(foo, E / F),
        E == F,
        write(ok), nl,
        halt.
```

**Comment by dram** [comment]
Record a single variable will cause error:

```
:- initialization(main).

main :-
        recordz(foo, A),
        recorded(foo, X),
        write(ok), nl,
        halt.

main :-
        write(error), nl,
        halt.
```

**Comment by dram** [comment]
And another problem:

```
:- initialization(main).

main :-
        T =.. [f, A],
        recordz(foo, g(B)),
        findall(X, recorded(foo, X), L),
        write(L), nl,
        halt.
```

Output:

```
% tpl foo.pro
[g(f(A))]
```

Should be `[g(B)]`.

**Comment by dram** [comment]
Sorry, but there is still some problem, e.g.

```
:- initialization(main).

foo(X, T) :- T =.. [f, X].

main :-
        foo(X, T0),
        recordz(bar, bar(T0, h(X))),
        recorded(bar, T1),
        write(T1), nl,
        halt.
```

Output:

```
% tpl foo.pro
bar(f(_137),h(_138))
```

Which I think should be `bar(f(_137),h(_137))`.

**Comment by dram** [comment]
A regression caused by previous fix:

```
:- initialization(main).

foo(N, X) :-
        recorded(foo, [N, X]).

main :-
        recordz(foo, [1, a]),
        recordz(foo, [2, b]),
        foo(N, b),
        write(N), nl,
        halt.
```

Output:

```
% tpl foo.pro
1
```

Which I think should be `2`.

**Comment by dram** [comment]
Another problem:

```
:- initialization(main).

main :-
        recordz(foo, _),
        findall(A, recorded(foo, A), L),
        write(L), nl,
        L = [X],
        write(X), nl,
        halt.
```

Output:

```
% tpl foo.pro
[_5]
_4
```

I think these two variables should be identical.

**Comment by dram** [comment]
And following code will cause `CYCLIC TERM` error:

```
:- initialization(main).

main :-
        append([foo], [A, B], L),
        T =.. L,
        write(T), nl, halt.
```

**Comment by infradig** [comment]
I would have thought so, but _4 & _5 are bound variables so I am putting it
down to printing at the moment. I'd like to know why though.

**Comment by infradig** [comment]
It's probably because of findall, which has to create new variables bound
to the originals. It will have  higher number (the _5). I still think it
just misleading printing.

**Comment by infradig** [comment]
Univ is a different story, it is really getting to me.

**Comment by infradig** [comment]
Ok, this is fixed and i'm convinced univ/2 is now correct. However 0229-6
and 0229-8 report anomalies but i'm pretty sure it's due to how bound
variables are printed and is not trivially fixed, though I will think on it.

**Comment by infradig** [comment]
I sueggest leaving #229 open.

**Comment by dram** [comment]
I'm afraid 0229-6 is not a printing problem, e.g. following code will fail:

```
:- initialization(main).

foo(X, T) :- T =.. [f, X].

main :-
        foo(X, T0),
        recordz(bar, bar(T0, h(X))),
        %listing,
        recorded(bar, T1),
        bar(f(A), h(B)) = T1,
        A == B,
        write(ok), nl,
        halt.

main :-
        write(error), nl,
        halt.
```

But interstingly, following code works:

```
:- initialization(main).

foo(X, T) :- T =.. [f, X].

main :-
        foo(X, T0),
        recordz(bar, bar(T0, h(X))),
        %listing,
        recorded(bar, T1),
        bar(f(A), h(A)) = T1,
        write(ok1), nl,
        bar(f(B), h(C)) = T1,
        B == C,
        write(ok2), nl,
        halt.
```

**Comment by infradig** [comment]
I think univ/2 is correct now and the fault is with record &/- recorded
(ie. assert &/- clause).

**Comment by dram** [comment]
Cool!

Now 74 tests passed.

**Comment by dram** [comment]
Seems that `=../2` is still buggy, e.g.:

```
:- initialization(main).

main :-
        T =.. [foo, A, B],
        A = B,
        (T = foo(X, Y), X == Y -> write(ok1), nl ; true),
        (T = foo(X, Y), X == Y -> write(ok2), nl ; true),
        halt.
```

Trealla only output `ok1`, GProlog, SWI and Yap all output both `ok1` and `ok2`.

**Comment by dram** [comment]
Still has problem:

```
:- initialization(main).

main :-
        _ = [C, D],
        T =.. [foo, A, B],
        A = B,
        T = foo(C, D),
        (T = foo(X, Y), X == Y -> write(ok), nl ; true),
        halt.
```

These tracing lines are suspicious:

```
...
Call: (foo(_5, _5)=foo(_2, _3))
Exit: (foo(_2, _3)=foo(_2, _3))
...
```

**Comment by dram** [comment]
Cool!

With this fix, now 86 ?-Prolog tests passed.

**Comment by dram** [comment]
Another problemm, which is triggered by [`dcg_fold_pairs`](https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/lib/dcg.pl?#dcg.pl-187:214) in ?-Prolog:

```
:- initialization(main).

foo(([A, _], [_, B]), ([A, B], _)).

main :-
        T1 = ([X, Y], [Y, f(_)]),
        foo(T1, T2),
        T2 =.. L, write(L), nl,
        halt.
```

Output:

```
% tpl foo.pro
[,,[_2,f(f(_4))],_133]
```

Which I think should be `[,,[_2,f(_4)],_133]` (one less level of `f()`).

**Comment by infradig** [comment]
Ok, i forgot to fix going the other way. The cell numbering is different so
I have fixed up some of the expected results.

**Comment by infradig** [comment]
Ok, that change seems to have messed up running 'pc'.

**Comment by dram** [comment]
Now 91 ?-Prolog tests passed.
