### ISSUE TITLE
Writing out multiline atom lost newlines

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#23]
For following code:

```
main :- write('foo
  bar
  baz'), nl, halt.
```

Trealla will output without newlines, e.g.:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 30 2016
foo  bar  baz
Halted
```

SWI and Yap will write with newlines preserved. GProlog does not seem to support multiline atom.

I think behavior like SWI and Yap is preferred, if we try to support multiline atom.

**Comment by infradig** [comment]
Interesting, never thought of that.

**Comment by dram** [comment]
Newlines seem to be lost again. I'll reopen this one.

**Comment by dram** [comment]
This one is back.

**Comment by infradig** [comment]
Got fixed with the other one. I had them reversed in meaning.

**Comment by dram** [comment]
For this test case, spaces before `bar` and `baz` have been lost, I'll reopen this.

**Comment by infradig** [comment]
I'm seeing the expected behaviour for this.

**Comment by infradig** [comment]
Note: neither SWI nor Yap output a leading space before bar and baz.

**Comment by dram** [comment]
I tested in SWI 6.6.6 and Yap 6.3.3, both of them preserve those leading whitespace, e.g.:

```
swipl -q -l foo.pro 
foo
  bar
  baz
```

```
yap -q -l foo.pl 
foo
  bar
  baz
% YAP execution halted
```

**Comment by infradig** [comment]
Hmm, i've got Yap 6.2.2 and it doesn't. Nor does SWI 7.2.3. So Yap add leading spaces and SWI removed it?

**Comment by infradig** [comment]
GProlog doesn't support multi-line atoms.

**Comment by infradig** [comment]
I think it should support them so I will make it so.  The prob is in trealla_readline where it eats blank lines.

**Comment by dram** [comment]
Interesting. I check that in SWI 7.2.3, installed from FreeBSD ports, there have leading spaces:

```
% swipl -v
SWI-Prolog version 7.2.3 for x86_64-freebsd

% swipl -l foo.pro
foo
  bar
  baz
```

**Comment by dram** [comment]
According to [Conformity Assessment](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_assessment), multiline atom without `\` escape is not a standard feature (see no. 6).

**Comment by infradig** [comment]
I think this is ok now. Going with the leading space preserved.

**Comment by dram** [comment]
Cool! Fix in `devel` branch confirmed.
