### ISSUE TITLE
Unknown operator

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#238]
Following code will cause unknown operator error in Trealla, which runs ok in GProlog, SWI and Yap:

```
:- initialization(main).

main :-
        A = a(&&),
        write(A), nl,
        halt.
```

Output:

```
% tpl foo.pro
ERROR: unknown operator: '&&'
ERROR: consult 'foo.pro', line=4, '     A = a(&&),'
```

**Comment by dram** [comment]
Fix confirmed, thanks.

**Comment by dram** [comment]
An regression with recent change, e.g. following code works in GProlog, SWI and Yap:

```
:- initialization(main).

main :-
        A = a(&/&),
        write(A), nl,
        halt.
```

**Comment by dram** [comment]
Forgot to reopen this.

**Comment by infradig** [comment]
Closing this as it was only an error in the expected file keeping it alive.
