### ISSUE TITLE
UNKNOWN -> 'use_module/1'

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#24]
`use_module/1` seems to be unusable, e.g.:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 30 2016
?- use_module(dict).
ERROR: UNKNOWN -> 'use_module/1'
WARN: ERROR ABORT_NOTDYNAMIC

(0.000 s) no
?- 
```

BTW, [`using/1`](https://github.com/trealla-lang/trealla/blame/master/FEATURES.md#L37) is also not usable. e.g.:

```
?- using([dict]).
ERROR: UNKNOWN -> 'using/1'
WARN: ERROR ABORT_NOTDYNAMIC

(0.000 s) no
?- 
```

**Comment by infradig** [comment]
Yes, known problem. These are file directives ONLY at the moment. I need to make them actual predicates.

**Comment by infradig** [comment]
Somewhat related to this, the REPL currently runs a new query for each input. This has two consequences: 1) there is no memory between inputs, 2) the directives as above would have no staying power. So I have to change this behaviour before I can solve this issue. But will do soon for sure.

**Comment by infradig** [comment]
You can now do:

 ?- using(sys),now(T).

from the REPL. 

Also use_module should work. As long as they are on the same line (query).

**Comment by dram** [comment]
Not sure if I did something wrong, I can not use `use_module/1` for custom modules.

Following is a simple module:

```
:- module(foo).

hi :- write(hi), nl, halt.
```

Then I use `use_module(foo), foo:hi` in REPL, an error is occurred.

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  1 2016
?- use_module(foo), foo:hi.
ERROR: UNKNOWN -> '/2'
WARN: ERROR ABORT_NOTDYNAMIC

(0.000 s) no
?- 
```

**Comment by infradig** [comment]
Ok, use_module only really loads compiled-in modules. perhaps it should also look in the 'module' sub-dir and/or current dir and load from there? Not sure.

**Comment by dram** [comment]
Find another way:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  1 2016
?- consult(foo).

(0.000 s) yes
?- foo:hi.
hi
Halted
```

I'm a bit confused by `use_module/1`, `using/1` and `consult/1`, the differences between them are not quite clear.

**Comment by infradig** [comment]
Saying 'using(sys)' means you don't have to say 'sys:now(Secs)' you can just say 'now(Secs)' in your code. 

Calling 'use_module(Name)' is a lot like 'consult(Name)' except it does an implicit 'using(Name)' on the module.

**Comment by infradig** [comment]
Also, use_module can load compiled-in modules, whereas consult can't.

**Comment by dram** [comment]
Thanks, all clear now.

**Comment by infradig** [comment]
Actually, I think I will get rid of 'using' and let 'use_module' cover it. Very simple to do.

**Comment by dram** [comment]
Interesting that, I can not load modules using `consult/1` again, can not figure out how I did it before.

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  1 2016
?- consult(foo).

(0.000 s) yes
?- foo:hi.
ERROR: UNKNOWN -> 'hi/0'
WARN: ERROR ABORT_NOTDYNAMIC

(0.000 s) no
?- 
```

**Comment by dram** [comment]
My fault, `hi/0` need to be exported.
