### ISSUE TITLE
Regression: operator parsing error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#242]
Following code do not work with recent changes:

```
:- initialization(main).

main :-
        T = a-(b-c),
        write(T), nl,
        halt.
```

Output:

```
% tpl foo.pro
ERROR: syntax error, excess terms
ERROR: consult 'foo.pro', line=6, '     halt.'
```

**Comment by infradig** [comment]
Have spend the last day or so redoing parser. It was a confused mess that
had just built up over time, with lots of band-aids. Might be another day
or so.

**Comment by dram** [comment]
👍 No hurry, take your time.

**Comment by dram** [comment]
Cool! Fix confirmed.
