### ISSUE TITLE
Confused about context

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#249]
Encountered a bug in `posix:spawn` which related to contexts. e.g.:

```
:- initialization(main).

foo(X) :-
        posix:spawn(echo, [echo| X], Pid),
        posix:wait(process(Pid), wait(_, status(0)), [exited]).

main :-
        A = a,
        B = [a, A],
        foo(B), halt.
```

Second `a` will lost in result output.

The culprit are [those lines](https://github.com/trealla-lang/trealla/blob/89f06a6d301db54912492e63156628e0a880a0aa/src/bifs_posix.c#L233-L246), if I change them to something like [bif_iso_atom_codes](https://github.com/trealla-lang/trealla/blob/89f06a6d301db54912492e63156628e0a880a0aa/src/bifs_iso.c#L2418-L2448), it will works.

Still can not figure out when to use `q->latest_context` or `termN_ctx`.

**Comment by infradig** [comment]
Yes, you need to keep track of the context (like in atom_codes) as you
traverse a list.

Generally, named contexts for args are the way to go, as q->latest_context
just refers to the most recently accessed one.

**Comment by dram** [comment]
Thanks!
