### ISSUE TITLE
split_all/3, split_string/4 and atoms ends with seperator

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#251]
The behaviour of `split_all/3` and `split_string/4` are different from SWI and some other languages regarding to atoms ends with seperator, e.g.:

Trealla:

```
% tpl -q
?- sys:split_all('.#.', '.', L).
 L: ['',#]

true.
?-
```

SWI-Prolog:

```
% swipl -q
?- split_string('.#.', '.', '', L).
L = ["", "#", ""].

?-
```

Python:

```
% python
>>> '.#.'.split('.')
['', '#', '']
>>>
```

Javascript:

```
% nodejs
> '.#.'.split('.')
[ '', '#', '' ]
>
```

**Comment by infradig** [comment]
I may have messed those up with my whitespace chnages.

**Comment by dram** [comment]
For `split_all/3`, still has problem:

```
% tpl -q
?- sys:split_all('#.#.', '#.', L).
 L: ['','']

true.
?-
```

**Comment by dram** [comment]
Fix confirmed, thanks.
