### ISSUE TITLE
ABORT_NOTDYNAMIC when consulting indirect module

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#26]
For two modules,

`foo.pl`:

```
- module(foo, [hi/0]).

hi :- write(hi), nl.
```

`bar.pl`:

```
:- module(bar, [hi/0]).

:- consult(foo).

hi :- foo:hi.
```

Result in REPL:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  1 2016
?- consult(bar).

(0.000 s) yes
?- bar:hi.
ERROR: UNKNOWN -> '/2'
WARN: ERROR ABORT_NOTDYNAMIC

(0.000 s) no
?- 
```

**Comment by infradig** [comment]
If you do this:

In foo.pl:

:-module(foo, [hi/0]).
hi :- write(hi), nl.

In bar.pl:

:-module(bar, [hi/0]).
:-use_module(foo).
hi :- foo:hi.

You get:

?- use_module('bar.pl').
?- bar:hi.
hi

So, with modules, always use 'use_module' not 'consult'. Because 'consult' does not export the namespace.

**Comment by dram** [comment]
According to your [comment](https://github.com/trealla-lang/trealla/issues/24#issuecomment-264065044), I thought that `use_module/1` will import all exported symbols into current namespace, while `consult/1` will not. Except that, this two are the same.

Have I misunderstood?
