### ISSUE TITLE
False cyclic term detection

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#27]
For following code, Trealla will report a false cyclic term detection:

```
last_element([], Out) :- Out = nil.
last_element([Arg|Rest], Out) :- write(Arg), last_element(Rest, Out).

foo(A, B, Out) :- last_element([A|B], Out).
bar(A, B) :- foo(A, [B], Out).

main :- bar(a, b), halt.
```

Trealla output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  2 2016
aWARN: ERROR ABORT_MAXDEPTH - CYCLIC TERM
```

There is no problem in GProlog and SWI an Yap.

**Comment by dram** [comment]
Simply test case further:

```
foo([A]) :- write(A), halt.
bar(A, B) :- foo(B).
baz(A, B) :- bar(A, [B]).

main :- baz(a, b).
```

**Comment by dram** [comment]
After enable `DEBUG` in `jela.c`, I found following unification is not correct, `bar(a,[b]) <==> bar(a,b)` should be `bar(a,[b]) <==> bar(A,B)`:

```
---
### match : baz(a,b) <==> baz(A,B)
### unify_term baz(a,b) : baz(A,B)
### unify_term a : A
### unify_term b : B
###[ try_me ] ==> size=0, choice_point=2, curr_choice=1, env_point=0
###[ execute_term ] ==> size=0, choice_point=3, curr_choice=2, env_point=0
###[ follow ] ==> size=2, choice_point=3, curr_choice=2, env_point=2
###[ allocate_frame ] ==> size=2, choice_point=3, curr_choice=2, env_point=2
### prepare_frame size=2, curr_choice=2, env_point=2
### match : bar(a,[b]) <==> bar(a,b)
### unify_term bar(a,[b]) : bar(a,b)
### unify_term a : A
### unify_term [B] : B
...
```

**Comment by dram** [comment]
Simplify even more:

```
bar(A) :- write(A), halt.
foo(A) :- bar([A]).

main :- foo(a).
```

**Comment by infradig** [comment]
Yep, I am onto it, but have limited time at the moment.

**Comment by dram** [comment]
No hurry, take your time.

**Comment by infradig** [comment]
Change the last line to this:

main :- B=1, foo(a).

and it works, For some reason main was getting a frame-size of 0 allocated, when it should be 1. This works for the earlier examples you posted as well.

Now to find out why...

**Comment by infradig** [comment]
Actually I think now that explanation was bogus! But it's something related to that.

**Comment by infradig** [comment]
Also, 

  main :- X=a, foo(X).

works as well.

**Comment by infradig** [comment]
I was close, it seems creating a choice-point with zero frame-size is the cause.  Now I have something to work with...

**Comment by dram** [comment]
Wow, Excellent!

Thanks!

BTW, I find that following line in jela debug info is not quite right, `[A] <==> A` should be `[a] <==> A`?

```
...
### match : bar([a]) <==> bar(A)
### unify_term : bar([a]) <==> bar(A)
### unify_compound : bar([a]) <==> bar(A)
### unify_term : [A] <==> A
...
```

**Comment by infradig** [comment]
You're right, it still prints the debug info incorrectly. But the result is right.
