### ISSUE TITLE
Backtracking cause infinite loop

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#28]
Following code will cause infinite loop in Trealla, while it's ok in GProlog, SWI and Yap.

I think it is caused by backtracking problem.

```
qux(A, B) :- write(A).

foo([]).
foo([X|Rest]) :- qux(X, a), foo(Rest).

bar(b(1)).

baz(A, B, C, D) :- D = ''.

main :- foo([a, b]), bar(B), baz(a, b, C, D), fail.
main :- halt.
```

**Comment by infradig** [comment]
Hmm, change to:

foo([]) :- !.
foo([X|Rest]) :- qux(X, a), foo(Rest).

and the cut fixes it. Will look into it...

**Comment by dram** [comment]
This fix cause another problem, e.g.:

```
qux(A) :- write(A).
baz([H|T], X) :- qux(H), baz(T, X).
bar(A) :- baz(A, B).
foo(A, B) :- bar([A, B]).

main :- foo(a, b), halt.
```

`tpl` output:

```
% ./tpl foo.pl
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  9 2016
WARN: ERROR ABORT_MAXDEPTH - CYCLIC TERM
```

**Comment by infradig** [comment]
bar(B) :- write(B), halt.
foo(A) :- bar([A]).
main :- foo(a).

**Comment by dram** [comment]
With this fix, the infinite loop of first example will come back...

**Comment by infradig** [comment]
I tested that one. I'll look again...

**Comment by infradig** [comment]
I tested this:

  qux(A, B) :- write(A).

  foo([]).
  foo([X|Rest]) :- qux(X, a), foo(Rest).

  bar(b(1)).

  baz(A, B, C, D) :- D = ''.

  main :- foo([a, b]), bar(B), baz(a, b, C, D), fail.
  main :- halt.

and it is working fine, same result as swi etc.

**Comment by infradig** [comment]
Oops, sorry, my mistake.

**Comment by dram** [comment]
I encountered another case to cause infinite loop, not sure if it's related. e.g.:

```
baz([]).
baz([_|T]) :- baz(T).

bar(A, _) :- baz(A).

foo(A) :- bar(A, _), write(1), nl.

main :- foo([a]), foo([b]), fail.
main :- halt.
```

**Comment by infradig** [comment]
Fixed, but only by turning off some optimization again, until I think some things out more.
