### ISSUE TITLE
A possible backtracking bug?

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#3]
Following code runs with expected result in gprolog and SWI:

```
upto(N, X) :- N > 0, N1 is N - 1, upto(N1, X).
upto(N, X) :- N > 0, X = N.

main :-
  \+ (upto(3, I), upto(I, J), \+ (write([I, J]), nl)), halt.
```

Expected result is:

```
[1,1]
[2,1]
[2,2]
[3,1]
[3,2]
[3,3]
```

But in Trealla, result is:

```
[1,1]
[3,1]
[3,2]
[3,3]
```

**Comment by trealla-lang** [comment]
This does not surprise me, probably related to the disjunction code.

**Comment by trealla-lang** [comment]
I rewrote the test in a non-disjunctive way:

 upto(N, X) :- N > 0, N1 is N - 1, upto(N1, X).
 upto(N, X) :- N > 0, X = N.

 main :- upto(3, I), upto(I, J), write([I, J]), nl, fail.
 main :- halt.

And the problem persisted.

So then I ran it with -O0 (no optimization) and got the expected result.

**Comment by trealla-lang** [comment]
Temp fix by disabling an optmization. I will look into that again later.

**Comment by infradig** [comment]
Did I say disjunctive? Meant negation.

**Comment by dram** [comment]
I revert that temp fix, and rebuild Trealla using `make debug`, which I think no optimization is enabled, but this problem still exists.

Am I do anythng wrong?

One suspicious point is that in `make debug` mode, sources are compiled with command `cc -Isrc -O3 -O0 -g -Wall ...`, not sure if `-O3` can be overrode by following `-O0`.

**Comment by infradig** [comment]
I believe -O0 does override.

When I said -O0 earlier I was referring 'tpl -O0' same as 'tpl --noopt', not compilation of the program.

Thanks for all the effort you've put into this.

**Comment by dram** [comment]
Oh, I see. Confirmed.

Thank you for your Trealla, I really like the idea of combining Prolog and Erlang, also the emphasis of datastore and networking.

**Comment by infradig** [comment]
Issue #13 (or something) has caused this to fail again.

**Comment by dram** [comment]
This testing code broken again after fix of #17, e.g.:

```
% ./tpl ../foo.pl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 28 2016
[1,1]
Halted
```

**Comment by dram** [comment]
This one is still incorrect, I'll reopen this issue so that it will not be forgotten.

**Comment by dram** [comment]
Find something interesting.

I simplified this test case a bit, following code can also reproduce this problem:

```
main :- \+ (member(I, [1,2,3]), \+ (write(I), nl)), halt.
```

But with a little adjustment, following code can loop are numbers correctly:

```
main :- \+ (member(I, [1,2,3]), \+ write(I)), nl, halt.
```

**Comment by infradig** [comment]
This is probably also related to the new issue with parenthesis. For instance:

 main :- (write(1), write(2)), nl.

never gets to the 'nl'.
