### ISSUE TITLE
Multiline clause support for input redirection mode

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#33]
It seems that in input redirection mode, multiline clause is executed separately instead of a whole.

For example, for following shell code:

```
tpl <<EOF
fail,
write(non_reachable), nl
EOF
```

Trealla's output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  5 2016

(0.000 s) no
non_reachable

(0.000 s) yes
```

BTW, it would be nice to make Trealla support consulting source from here document instead of file, so that pieces of Prolog code can be embedded in shell script directly. Currently, input redirection is for REPL, it's nice for IDE integration, but a bit clumsy for scripting.

**Comment by infradig** [comment]
I'll have  a look at last part...

**Comment by infradig** [comment]
Did you mean:

./tpl
 [user].
blah blah
CTRL-D

???

**Comment by dram** [comment]
I mean to embed Prolog code into a shell script, e.g. file `foo.sh`:

```
#!/bin/sh

ARG=$1

tpl --goal=main --consult - <<EOF
main :- write($ARG), nl.
EOF
```

Here `--consult -` is used to mean consulting content from `stdin` as a file, as meaning of `tpl` without any option has alway been taken by REPL.

**Comment by dram** [comment]
Affected by changes made for #56.

**Comment by dram** [comment]
This one is also back.

**Comment by dram** [comment]
Something is still not quite right, e.g.:

```
tpl <<EOF
A = 1.
B = 2.
EOF
```

Output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 18 2016
 A: 1 
(0.000) true.
DEBUG: orphaned=7
```

Two problems:

1. Result of `B = 2` is lost.
2. `orphaned` warning.

I'll reopen this.

**Comment by infradig** [comment]
Orphans were the missing term(s).

**Comment by dram** [comment]
Now a segmentation fault is triggered for this test case.

**Comment by infradig** [comment]
This works too:

./tpl <<EOF
A=1.
B=2,
C=3.
EOF

Trealla v0.1alpha, 64-bits (int=128-bits), Dec 18 2016
 A: 1 
(0.000) true.
 B: 2 C: 3 
(0.000) true.

**Comment by dram** [comment]
Do you mean `devel` branch?

I checked that branch, both your example and following code run correctly:

```
tpl <<EOF
A = 1.
B = 2.
EOF
```

But following code still cause segmentation fault:

```
tpl <<EOF
fail,
write(non_reachable), nl
EOF
```

**Comment by infradig** [comment]
Ok, this one:

tpl <<EOF
fail,
write(non_reachable), nl
EOF

needs a final dot. I will fix that...

**Comment by dram** [comment]
I'm not aware of that...

An error message instead of segmentation fault is enough.

**Comment by infradig** [comment]
Now does:

$ ./tpl -q <<EOF
fail,
write(unreachable)
EOF
ERROR: parse -> EOF

false.
DEBUG: orphaned=6

So i will do a bit more work on it.

**Comment by dram** [comment]
Follow shell script will cause segmentation fault:

```
tpl -q <<EOF
halt
EOF
```

Following is backtrace:

```
Core was generated by `tpl -q'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000040c0f6 in xref_rule (l=0x6578a90, n=0x0) at src/trealla.c:2477
2477            node *tmp = NLIST_FRONT(&n->val_l);
(gdb) bt
#0  0x000000000040c0f6 in xref_rule (l=0x6578a90, n=0x0) at src/trealla.c:2477
#1  0x000000000040c922 in query_parse_file (self=0x66970c0, src=0x0, fp=0x7fac0dc9c4e0 <_IO_2_1_stdin_>) at src/trealla.c:2640
#2  0x0000000000404842 in main (ac=2, av=0x7fff963289c8) at tpl.c:388
```

**Comment by dram** [comment]
Can be closed now.
