### ISSUE TITLE
number_codes/2 and number_chars/2 failed to convert float numbers

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#34]
It seems that both `number_codes/2` and `number_chars/2` failed to convert float numbers, e.g.:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  5 2016
?- number_codes(N, "1.0").
WARN: ERROR ABORT_INVALIDARGNOTLISTORVAR

(0.000 s) no
?- number_chars(N, ['1', '.', '0']).
WARN: ERROR ABORT_INVALIDARGNOTINT

(0.000 s) no
?-
```

I have checked that ALS, GProlog, SWI and Yap all convert correctly.

**Comment by infradig** [comment]
Didn't think of floats.

**Comment by infradig** [comment]
Note: Trealla doesn't currently support double-quotest as number codes. It's treated same as single-quotes.

**Comment by dram** [comment]
Not aware of that, and it seems that character literal syntax is not supported either, e.g. `0'a`.

BTW, `number_codes/2` is still not correct. e.g.:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  7 2016
?- number_codes(N, [49, 46, 48]).
N: 80 
(0.000 s) yes
?- 
```

Which should be `1.0`.
