### ISSUE TITLE
Spread long atom into multiple lines

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#36]
Trealla's interpretation of line continuation symbol `\` is different from ALS, GProlog, SWI and Yap, e.g.:

```
main :- write('foo\
bar'), nl.
```

For above code, Trealla will print `foo` and `bar` in seperate lines, while other implementations mentioned above all print `foobar` in a single line.

Also see [Conformity Assessment](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_assessment) no. 7 for other implementations.

**Comment by infradig** [comment]
Never knew that.

**Comment by dram** [comment]
Now only `foo` is printed out, with `bar` lost.

I'll reopen this issue.

**Comment by infradig** [comment]
I get the expected behaviour now.

**Comment by dram** [comment]
And also this issue.

**Comment by infradig** [comment]
Got them the wrong way around.
