### ISSUE TITLE
member/2 does not support compound term

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#37]
`member/2` does not match compound terms, e.g.:

```
member(foo(Foo), [foo(1), bar(2)])
```

For implementations support `member/2` (I have tested ALS, GProlog and SWI), `Foo` will be unified to `1`.

**Comment by infradig** [comment]
Wow was that hard to track down, a simple index off by one.

**Comment by dram** [comment]
Exciting!

But it seems that it still has problem. When I try in REPL, I have stumbled into an infinite loop:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  8 2016
?- member(foo(Foo), [foo(1), bar(2)]).
 (abort=a,trace=t,next=;): 
(abort=a,trace=t,next=;): 
(abort=a,trace=t,next=;):
...
```

**Comment by infradig** [comment]
Yes, I noticed that.

**Comment by dram** [comment]
It seems that results are correctly unified now, but not displayed. e.g.:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  8 2016
?- member(foo(Foo), [foo(1), bar(2)]).
(abort=a,trace=t,next=;): 

(0.000 s) no
?- 
```

**Comment by infradig** [comment]
I think I did 2 updates, and fixed that on the second.

**Comment by dram** [comment]
I double checked that, this problem still exists:

```
% git clean -dfx
% git pull
% make OPT="-std=c11 -O0 -g"
% ./tpl 
Trealla v0.1alpha, 64-bits (int=128-bits), Dec  8 2016
?- member(foo(Foo), [foo(1), bar(2)]).
(abort=a,trace=t,next=;): 

(0.000 s) no
?- halt.
Halted
WARN: orphaned=3
```

**Comment by dram** [comment]
Fix confirmed! :tada:
