### ISSUE TITLE
Consult from stdin

### ISSUE THREAD

**Issue by infradig** [trealla-lang/trealla#38]
I mean to embed Prolog code into a shell script, e.g. file foo.sh:

#!/bin/sh

ARG=$1

tpl --goal=main --consult - <<EOF
main :- write($ARG), nl.
EOF
Here --consult - is used to mean consulting content from stdin as a file, as meaning of tpl without any option has alway been taken by REPL.

**Comment by infradig** [comment]
tpl --goal=main --consult <<EOF
main :- write(hello), nl.
EOF

**Comment by dram** [comment]
:+1: Thanks!
