### ISSUE TITLE
atom_codes/2 for UTF-8 atoms

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#39]
It seems that `atom_codes/2` does not understand UTF-8 atoms, e.g.:

```
main :- atom_codes('一二三', L), write(L), nl, halt.
```

SWI and Yap will output `[19968,20108,19977]`, but Trealla's result is `[-28,-72,-128,-28,-70,-116,-28,-72,-119]`.

**Comment by infradig** [comment]
Yah, utf8 support is just theoretical at this point! Working on it...
