### ISSUE TITLE
Warn name conflict when importing modules

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#40]
For following modules, `tpl` will run `foo.pl` silently without any error message, SWI will print an error, and YAP will prompt with choices to resolve name conflict.

Program `foo.pl`:

```
:- use_module(bar).
:- use_module(baz).

main :- hi, halt.
```

Module `bar`:

```
:- module(bar, [hi/0]).

hi :- write('hi bar'), nl.
```

Module `baz`:

```
:- module(baz, [hi/0]).

hi :- write('hi baz'), nl.
```

**Comment by infradig** [comment]
Current practice is that use_module does not import unqualified names. You have to specify bar:hi or baz:hi.
