### ISSUE TITLE
How to resolve name conflicts?

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#41]
it is related to issue #40 and #26, e.g. for following two modules, how can I use both of their `hi/0` in another module?

Module `bar`:

```
:- module(bar, [hi/0]).

hi :- write('hi bar'), nl.
```

Module `baz`:

```
:- module(baz, [hi/0]).

hi :- write('hi baz'), nl.
```

I think there are two possible approaches:

1. Provide a mechanism to load modules without importing names into current namespace.
2. Load modules automatically according to module prefix in names, which is similar to Erlang.

**Comment by infradig** [comment]
Currently:

:-use_module(bar).
:-use_module(baz).

  main :- hi.

will output 'hi bar' because it finds the first one loaded. of course you can do:

  main :- baz:hi.

to select the one you want.

**Comment by infradig** [comment]
In regard to Issue #40, I suppose I could add a conflict warning.

**Comment by dram** [comment]
If we go to warn name conflicts in regard to #40, then it would is more necessary to allow modules be loaded without import names, or this kind of warnings will be hard to be suppressed.

BTW, for large projects, I'd like to always use explicit module prefix, import names into current namespace is similar to Python's wildcard imports `import *`, which is not recommended, see [here](https://www.python.org/dev/peps/pep-0008/#imports) and [here](http://stackoverflow.com/a/2386740/5180632).

Similarly, Erlang community seems to prefer to avoiding `import`, see [here](http://erlang.org/pipermail/erlang-questions/2007-July/027776.html), [here](http://learnyousomeerlang.com/modules#module-declaration) and [here](https://github.com/inaka/erlang_guidelines#dont-import).

**Comment by infradig** [comment]
I agree, I have recently gone to using module prefix in the apps. I think I will enforce that.

**Comment by infradig** [comment]
But keep for the builtin modules sys ,net, proc etc.

**Comment by dram** [comment]
Just find that, in SWI and YAP, `use_module(name, [])` can be used to load modules without import names, e.g.:

```
:- use_module(bar, []).
:- use_module(baz, []).

main :- bar:hi, baz:hi, halt.
```

**Comment by dram** [comment]
Am I miss something? Do we have mechanism similar to `use_module(name, [])` now?

**Comment by infradig** [comment]
Current practice is that use_module does not import unqualified names. You have to specify bar:hi or baz:hi.

**Comment by dram** [comment]
Nice! I like this style.
