### ISSUE TITLE
Unquoted UTF-8 atom

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#44]
As already mentioned in #43, SWI support unquoted UTF-8 atoms.

Currently, In Trealla UTF-8 atoms need to be quoted. I think SWI's behavior will make UTF-8 atoms much easier to be used.

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 12 2016
?- A = '一二三'.
 A: '一二三' 
(0.000 s) yes
?- A = 一二三.
ERROR: unknown operator: '一二三'
ERROR: parse -> A = 一二三.

(0.000 s) no
?- 
```

**Comment by infradig** [comment]
Yes, I need to make parsing utf-8 aware to do that.

**Comment by infradig** [comment]
A start:

Trealla v0.1alpha, 64-bits (int=128-bits), Dec 12 2016
?-  A = 一二三.
 A: 一二三 
(0.000 s) yes

**Comment by infradig** [comment]
I'll have to check the builtin functions...
