### ISSUE TITLE
Key names in HTTP stash

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#47]
I find that there are several uppercase keys for request and response infos in HTTP stash, can we name them according to CGI [RFC 3875](https://tools.ietf.org/html/rfc3875)? So that learning curve can be lowered a bit.

Also I find there are two version of key value pairs in stash for HTTP headers, e.g. `HTTP_CONTENT_LENGTH` and `Content-Length`. It seems a bit redundant, as we can get headers from stash directly, I think there is no needed to add `HTTP_*` for headers.

BTW, as meta infos and headers are both stored in a single stash, it may cause name conflict, I have thought out two possible solutions:

1. Use separate stashs for those two.
2. Take advantage of case insensitivity of HTTP headers, we can store meta infos in all uppercase, and headers in lowercase.

**Comment by infradig** [comment]
Have removed HTTP_ prefix. and non-standard meta variables. Meta variables and headers can be distinguished by use of underscore '_' vs hyphen '-'.

**Comment by dram** [comment]
Nice! I found a [discussion](http://stackoverflow.com/questions/22856136/why-underscores-are-forbidden-in-http-header-names) shows that although underscore `_` is allowed for header names in HTTP, it is not recommended in common HTTP servers, so it is safe to be used to distinguish meta variables from headers.

BTW, according to [4.1. Request Meta-Variables](https://tools.ietf.org/html/rfc3875#page-10) in RFC 3875, I think its better to rename `STATUS` to `X_STATUS`, as it is not a standard meta-variable.
