### ISSUE TITLE
Segmentation fault for unbalanced parentheses

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#49]
Unbalanced parentheses will cause segmentation fault, e.g.:

```
main :- foo(bar, halt.
```

**Comment by infradig** [comment]
Yes, been around a while...

**Comment by dram** [comment]
If I create a source file with following code and without last newline before EOF, the code in error message will be a bit mess.

```
:- initialization(main).

main :- foo(bar, halt.
```

I'll reopen this issue.

**Comment by infradig** [comment]
When consulting this in a file I see an end_of_file warning. But consulting stdin I don't...

**Comment by infradig** [comment]
Anyway it should say a mismatched parenthesis.
