### ISSUE TITLE
Use `INCBIN` to handle library files instead of `xxd`?

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#5]
Just FYI, I read [Eve](https://github.com/witheve/Eve) code not long before, and find that they use `INCBIN` and `ASCIZ` ASM directives to include source files into C binary, it can be a replacement of `xxd` in Trealla, although I'm not sure the portability situation of them.

See [wrap.S](https://github.com/witheve/Eve/blob/0.1/build/wrap.S) and [Makefile](https://github.com/witheve/Eve/blob/0.1/build/Makefile) for more details. (That code was used in one of their previous prototypes which using Lua, now it seems that they have turned to TypeScript)

**Comment by infradig** [comment]
For what it's worth, xxd is available with the VIM package on systems where it isn't a first-class package, such as FreeBSD.

**Comment by dram** [comment]
Another alternative would be `objcopy`. See this [SO answer](http://stackoverflow.com/a/2339839/5180632) for more detail.

**Comment by infradig** [comment]
Yeah, objcopy looks good for Linux and BSD.

**Comment by dram** [comment]
Find a detailed list of [methods](https://www.devever.net/~hl/incbin), seems that `ld` is better than `objcopy` for Linux and BSD. I'm not family with Windows, so not sure which one is better when considering portability.
