### ISSUE TITLE
halt/1 does not halt

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#52]
It seems that `halt/1` in Trealla does not have any effect, while GProlog, SWI and YAP will exit with supplied integer.

**Comment by infradig** [comment]
halt(N) where N>1 works. I will fix.

**Comment by dram** [comment]
Now both `halt` and `halt(0)` cause Trealla exit with status `1` instead of `0`, which is inconsistent with GProlog, SWI and YAP.
