### ISSUE TITLE
Redundant parentheses cause memory corruption

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#54]
Following code cause memory corruption:

```
main :- (foo, (bar(baz))), halt.
```

**Comment by infradig** [comment]
Yep,

  main :- (bar(baz)), halt.

is enough.

**Comment by dram** [comment]
Not sure if related, following code does not parse correctly:

```
main :- write(a), nl, (write(b), nl), halt.
```

Listing:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 16 2016
main :- 
        write(a),
        nl(write(b),nl),
        halt.
```

**Comment by dram** [comment]
According to valgrind's result, those lines [trealla.c#L2058-L2063](https://github.com/trealla-lang/trealla/blob/620717d575c516f72abbcb4522baba8bef3febb7/src/trealla.c#L2058-L2063) are suspicious.

After I commented them out, memory corruption disappeared.

**Comment by infradig** [comment]
Yes, very suspect. Can't imagine what it is supposed to be doing.

**Comment by infradig** [comment]
Perhaps it was supposed to be NLIST_POP_FRONT, not NLIST_FRONT.

**Comment by infradig** [comment]
Anyway, it still doesn't parse correctly.

**Comment by dram** [comment]
Now your test case will cause an infinite loop:

```
main :- (bar(baz)), halt.
```

**Comment by infradig** [comment]
Now for this:

main :- write(a), nl, (write(b), nl), halt.

Seems ok now?

**Comment by dram** [comment]
Cool! Fix confirmed in devel branch. I'll close this issue.
