### ISSUE TITLE
Failed to parse multiple rules in single line

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#57]
Trealla failed to parse multiple rules in a single line, e.g.:

```
:- initialization(main). main :- write(hi), nl, halt.
```

Error output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 16 2016
ERROR: unknown operator: '.'
ERROR: consult 'foo.pl'
>>> Syntax error,line=1
>>> , nl, halt.
?- 
```

**Comment by infradig** [comment]
Trealla doesn't support multi rules per line at the moment, they are pretty horrendous. The '.' must terminate the line. It will take a major rethink of input processing to fix this so i'm labelling "won't fix" for now.

**Comment by infradig** [comment]
Note, for same reason Trealla can't do this:

~/trealla$ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.2.3)
?- read(S1), read(S2).
|: hello1. hello2.
S1 = hello1,
S2 = hello2.
?- halt.

**Comment by infradig** [comment]
Ok, feeling guilty now. Enhancement...
