### ISSUE TITLE
Parsing error if source file does not have newline before EOF

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#58]
It seems that if source file does not have newline before EOF, Trealla will not parse last rule. e.g.:

```
:- initialization(main).

main :- write('hi'), nl, halt.
```

Output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 17 2016
ERROR: UNKNOWN -> 'main/0'
ERROR: ERROR ABORT_NOTDYNAMIC
```

**Comment by dram** [comment]
It seems that this problem still exists.

**Comment by dram** [comment]
This issue is back again.

**Comment by infradig** [comment]
Yes, did a reworking of parsing.This was one i didn't re-test.

**Comment by dram** [comment]
You are faster! :D

**Comment by dram** [comment]
Fix confirmed, I'll close this issue.

**Comment by dram** [comment]
It is back again.

**Comment by dram** [comment]
This problem is back again, with another test case (no newline before EOF):

```
foo() :-
    bar(baz
        qux).
```

Output:

```
% tpl --ns foo.pl
Trealla v0.1alpha, 64-bits (int=128-bits), Feb  8 2017
ERROR: consult 'foo.pl', line=3, '        qux).'
INFO: consulted 'foo.pl': 8 terms
DEBUG: orphaned=4
```

**Comment by infradig** [comment]
I can't reproduce this.

**Comment by infradig** [comment]
foo() :-
    bar(baz
        qux).

Oops, yes this one.

**Comment by infradig** [comment]
Seems without the trailing LF it generates a parsing error, as it should. But with the LF it doesn't, when it should.

**Comment by dram** [comment]
Sorry, previous test case in incorrect, use following code (without end of file newline):

```
foo :-
    member(X,
           []), write(X).
```

Output:

```
% tpl --ns issues/0058.pro 
Trealla v0.1alpha, 64-bits (int=128-bits), Feb 15 2017
ERROR: premature end found
ERROR: consult 'issues/0058.pro', line=3, '           []), write(X).'
INFO: consulted 'issues/0058.pro': 7 terms
DEBUG: orphaned=4
```

I'll update trealla-tests repo.

**Comment by dram** [comment]
Thanks, fix confirmed.
