### ISSUE TITLE
number_chars/2 and number_codes/2 failed to unify

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#6]
`number_chars/2` and `number_codes/2` failed to unify numbers, see following REPL session:

```
% ./tpl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 21 2016
?- number_chars(N, ['1', '2', '3']).

(0.000 s) no
?- number_codes(N, [49, 50, 51]).

(0.000 s) no
?- 
```

I have checked in gprolog and swi, both unify `N` to `123`.

**Comment by infradig** [comment]
These arn'te implemented, yet.

**Comment by infradig** [comment]
Ditto atom_chars / atom_codes.
