### ISSUE TITLE
Inconsistent behavior after error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#66]
Currently, Trealla is a bit inconsistent when errors are occurred. e.g.:

For following code, Trealla will exit after reporting error:

```
:- initialization(main).
main :- foo:bar, halt.
```

For this one, Trealla will drop into REPL after reporting error:

```
:- initialization(main).
main :- sys:bar, halt.
```

**Comment by infradig** [comment]
Hopefully this is better:

andrew@andrew:~/trealla$ ./tpl --trace --consult <<EOF
:-initialization(main).
main :- net:foo.
EOF
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 20 2016
ERROR: in 'default', not exported 'net:foo/0'
andrew@andrew:~/trealla$ ./tpl --trace --consult <<EOF
:-initialization(main).
main :- bah:foo.
EOF

Trealla v0.1alpha, 64-bits (int=128-bits), Dec 20 2016
ERROR: in 'default', not exported 'bah:foo/0'
andrew@andrew:~/trealla$
