### ISSUE TITLE
Transfer trealla-tests repo into trealla-lang organization

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#68]
I'd like to transfer [trealla-tests](https://github.com/dram/trealla-tests) repo into [trealla-lang](https://github.com/trealla-lang) organization.

If it's OK to do that, I will cleanup it a bit (e.g. README, LICENSE...) and then move it here.

**Comment by infradig** [comment]
Sure

**Comment by infradig** [comment]
I was looking at it. I have changed the Trealla error messages a bit so it will mess things up no doubt.

**Comment by dram** [comment]
Done.

I'll update affected error messages.
