### ISSUE TITLE
get_code/2 cause tpl waiting for input after halt

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#71]
For following code, tpl will wait for input after halt:

```
:- initialization(main).

main :-
    open('foo.pro', read, Stream),
    get_code(Stream, C),
    close(Stream),
    write(C),
    halt.
```

**Comment by dram** [comment]
`get_code/1` and `get_char/1` still have problem, for following code:

```
:- initialization(main).

main :- get_code(C1), get_code(C2), write([C1, C2]), nl, halt.
```

If run interactively, it will still wait for input after halt.

If run as shell script, it will cause infinite loop, e.g.:

```
tpl -l foo.pro <<EOF
1
EOF
```

I'll reopen this issue.

**Comment by infradig** [comment]
The end of a query should now drain up to and including the newline, I believe.

**Comment by dram** [comment]
For this case:

```
:- initialization(main).

main :- get_code(C1), get_code(C2), write([C1, C2]), nl, halt.
```

If run this example interactively, enter a single character, and return, Trealla will write out two numbers (newline character is consumed) and halted, but waiting for input.

Output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 22 2016
1
[49,10]
Halted
```

It does not have problem if more then one characters are entered.

**Comment by dram** [comment]
`get_char/1` have similar problem.

**Comment by infradig** [comment]
Also get_byte/1
