### ISSUE TITLE
No error for terms adjoining without operators

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#72]
For following code, Trealla will run without error, but I think an error is more suitable.

```
main :- write(a) write(b), halt.
```

I have checked ALS, GProlog, SWI and YAP, all of them will report syntax error.

It may be related to #13.

**Comment by infradig** [comment]
Not a bug, a feature! :)

**Comment by dram** [comment]
OK.

Not sure whether that feature will complicate parser code, as it is already a bit complex.

Personally, I would prefer to write `,` explicitly, as Prolog allows any atom to be declared as operators, it will be hard to distinguish operator applications from plain separated terms if no `,` is used, e.g. not a quite real example:

```
:- op(700, xfx, unify).

X unify Y :- X = Y.

main :- foo unify A, write(A), halt.
```

I will close this issue.

**Comment by infradig** [comment]
No, I was joking.

**Comment by dram** [comment]
Aha, reopen it. :smile:

**Comment by dram** [comment]
Fix confirmed, thanks!
