### ISSUE TITLE
Failed to define empty atom as an operator

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#73]
It cause error to define empty atom as an operator, e.g.:

```
:- initialization(main).

:- op(500, xfy, '').

main :- write(1 '' 2), halt.
```

Output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 21 2016
ERROR: unknown operator: ' '
ERROR: consult 'foo.pro', line=5, 'main :- write(1 '' 2), halt.'
?- 
```

**Comment by infradig** [comment]
Interesting SWI 6 outputs a space in this case:

$ swipl -l ../trealla-tests/issues/0073.pro
1 2andrew@andrew:~/trealla$ 

$ yap -l ../trealla-tests/issues/0073.pro
12% YAP execution halted

**Comment by dram** [comment]
Also confirmed in SWI 7.

BTW, GProlog outputs two spaces.
