### ISSUE TITLE
Define a whitespace opeartor (' ') cause INVALIDARGNOTSTREAM error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#74]
Define a whitespace opeartor will cause `INVALIDARGNOTSTREAM` error, e.g.:

```
:- initialization(main).

:- op(500, xfy, ' ').

main :- write(1 ' ' 2), halt.
```

Output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 21 2016
ERROR: ERROR ABORT_INVALIDARGNOTSTREAM
```

I have checked GProlog, SWI and YAP, all run without error.

**Comment by infradig** [comment]
Interesting. I'd like to know the use-case for this...

**Comment by dram** [comment]
No a real use case, I use that operators (both `''` and `' '`) as a short hand to write out several atoms concatenated with whitespace, e.g.:

```
:- op(500, xfy, ' ').

main :- write(foo ' ' bar ' ' baz), nl, halt.
```

GProlog output:

```
foo   bar   baz
```
 
SWI output:

```
foo bar baz
```

YAP output:

```
foo   bar   baz
```

That is a bit tricky, so I think certainly I'll not use this for serious code.
