### ISSUE TITLE
Incorrect unification result in REPL

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#76]
For following source file `foo.pro`:

```
foo(bar).
```

Run with following script:

```
tpl foo.pro <<EOF
foo(A).
EOF
```

Result is not right:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 21 2016
 A: A 
(0.000) true.
```

`A: A` should be `A: bar`.

**Comment by infradig** [comment]
$ ./tpl samples/foo.pro <<EOF
foo(A).
EOF
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 21 2016
 A: bar 
(0.000) true.
