### ISSUE TITLE
Samples queens8 does not terminate when it should

### ISSUE THREAD

**Issue by infradig** [trealla-lang/trealla#79]
tpl samples/queens8 --goal=test

fails to terminate upon producing all solutions.

**Comment by dram** [comment]
If I load `queens8.pro` into REPL and query for `rangeList/3`, no result is shown:

```
% tpl queens8.pro 
Trealla v0.1alpha, 64-bits (int=128-bits), Dec 31 2016
INFO: consulted 'queens8.pro': 238 terms
?- rangeList(1, 8, Ns).

(0.000) false.
?-
```

**Comment by dram** [comment]
Extract `rangeList/3` and create another test case:

```
rangeList(M,N,[M]) :- M >= N, !.                                                
rangeList(M,N,[M|Tail]) :- M1 is M+1, rangeList(M1,N,Tail).                     
                                                                                
test :-                                                                         
  rangeList(1, 8, Ns), write(Ns), nl.
```

`test` will genearte infinite results, e.g.:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Jan 27 2017
?- [foo].
INFO: consulted 'foo': 60 terms

(0.000) true.
?- test.
[1,2,3,4,5,6,7,8]
(abort=a,trace=t,next=;):
[1,2,3,4,5,6,7,8,9]
(abort=a,trace=t,next=;):
[1,2,3,4,5,6,7,8,9,10]
...
```

In GProlog, SWI and Yap, there is only one result.

**Comment by dram** [comment]
It seems that `!` did not cut the choice point:

```
...
###[ follow ] ==> size=2, choice_point=19, curr_choice=18, env_point=32
Call: 8>=8
Exit: 8>=8
###[ follow ] ==> size=2, choice_point=19, curr_choice=18, env_point=32
Call: !
###[ trust_me ] ==> size=2, choice_point=19, curr_choice=18, env_point=32
Exit: !
###[ follow ] ==> size=2, choice_point=19, curr_choice=18, env_point=32
###[ proceed ] ==> size=2, choice_point=19, curr_choice=18, env_point=32
...
```

**Comment by dram** [comment]
If `optimize(inline)` is enabled, choice point is cutted:

```
...
###[ follow ] ==> size=2, choice_point=9, curr_choice=8, env_point=32
Call: 8>=8
Exit: 8>=8
###[ follow ] ==> size=2, choice_point=9, curr_choice=8, env_point=32
Call: !
###[ trust_me ] ==> size=2, choice_point=9, curr_choice=8, env_point=32
Exit: !
###[ follow ] ==> size=2, choice_point=8, curr_choice=8, env_point=32
###[ proceed ] ==> size=2, choice_point=8, curr_choice=8, env_point=32
...
```

**Comment by infradig** [comment]
Thanks. I hope to look at it this week.

**Comment by infradig** [comment]
In bifs_iso.c/bif_iso_and() if you comment out the allocate & try_me then queens8 works fine with/without optimize(inline). Now that is how it originally was, and how I believe it should be, optimally. Conjunction shouldn't need to create a choice-point.

Problem is with issue#3 then. So maybe I need to go back and look at that.

**Comment by dram** [comment]
After applying your suggested change, a test case in #54 is also affected: `halt` will not be executed then.

```
:- initialization(main).

main :- write(a), nl, (write(b), nl), halt.
```

Listing seems to be correct:

```
':-'(main,','(write(a),','(nl,','(','(write(b),nl),halt)))).
```

**Comment by infradig** [comment]
In Issue #3 if I change

  \+ (upto(3, I), upto(I, J), \+ (write([I, J]), nl)), halt.

to

  \+ (upto(3, I), upto(I, J), \+ call((write([I, J]), nl))), halt.

it works. The same solution applied to #54-2 above works. 

So I feel removing the allocate & try_me is the way to go and the optimal solution is close...

**Comment by dram** [comment]
One problem mentioned above still exists, "load queens8.pro into REPL and query for rangeList/3" has no result.
