### ISSUE TITLE
Obscure error message for unknown external terms

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#80]
The error message for unknown external terms is obscure, e.g.:

```
:- initialization(main).

main :- foo:bar, halt.
``` 

Error message:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Jan 22 2017
INFO: consulted 'foo.pro': 17 terms
ERROR: UNKNOWN -> '/2'
ERROR: ERROR ABORT_NOTDYNAMIC
```

I think `/2` should be `foo:bar/0`.

**Comment by infradig** [comment]
Note :/2 is an operator, usually used with tuples. If the left hand side is a defined module then it used for that purpose. I have made it a bit more explicit:

Trealla v0.1alpha, 64-bits (int=128-bits), Jan 22 2017
INFO: consulted 'samples/foo': 17 terms
ERROR: NOT CALLABLE -> ':/2'

I will ponder it some more though.

**Comment by dram** [comment]
Is `:/2` an extension of Trealla? I can not find description of it in FEATURES.md.

**Comment by infradig** [comment]
Yes it is, and no it's not in features. It should probably be left out and an op defined when needed: see samples/validate.pro test10 which does pseudo-JSON.

**Comment by infradig** [comment]
Also, Yap and GProlog support :/2. SWI uses it for dicts.

**Comment by dram** [comment]
Clear now, thanks!
