### ISSUE TITLE
Incorrect behavior for if-then-else

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#89]
For following test case, Trealla will output both `foo` and `bar`, GProlog, SWI and Yap only print out `foo`.

```
:- initialization(main).

main :-
  (a = a ->
     write(foo), nl,
     fail ;
   write(bar), nl), halt.
main :- halt.
```

**Comment by infradig** [comment]
It's the disjunction, you can simplify it to:

main :-
	((write(foo), nl, fail) ;
	 (write(bar), nl)), halt.
main :- halt.

**Comment by infradig** [comment]
Ignore that comment (I deleted it)!
