### ISSUE TITLE
Unification failed

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#92]
Following code show that there is something wrong with unification in Trealla:

```
:- initialization(main).

foo(L) :- [a|_] = L, write('foo'), nl.
bar([X|L]) :- foo([X|L]).

main :- bar([a]), halt.
```

GProlog, SWI and Yap will print out `foo`, but Trealla will quit silently.

**Comment by infradig** [comment]
Change:

  foo(L) :- [a|_] = L, write('foo'), nl.

to

  foo(L) :- L = [a|_], write('foo'), nl.

and it works.

**Comment by dram** [comment]
Change from `[a|_] = L` to `L = [a|_]` have no effect here.

**Comment by dram** [comment]
Sorry, please ignore previous comment, I think I have made something wrong.

**Comment by dram** [comment]
Cool!. Code related to contexts is much clear now.  :tada:
