### ISSUE TITLE
Another if-then-else problem

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#94]
For following code, GProlog, SWI and Yap will print out `foo`, but Trealla will not.

```
:- initialization(main).

main :- (a \= b, a = a -> write(foo) ; write(bar)), nl, halt.
```

**Comment by infradig** [comment]
This is probaly the same problem as #89.

**Comment by infradig** [comment]
I fixed this by effectively replacing 'A -> B' with 'A, !, B' as a textual paste. This is the logical equivalent. It does however mess with a listing output, since the underlying '->' is now gone. I might revisit this later.

**Comment by infradig** [comment]
Now can't use as an operator, so no '->(A,B)'. I'll have to do it differently.
