### ISSUE TITLE
Unification failed for variables used both as input and output

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#96]
For following code, which uses variable `X` both as input and output, Trealla will failed to unify. GProlog, SWI and Yap all print out `1` correctly.

```
:- initialization(main).

foo(A, B) :- A = 1, write(B), nl.

main :- foo(X, X), halt.
```

Output:

```
% tpl --ns foo.pl
Trealla v0.1alpha, 64-bits (int=128-bits), Feb 10 2017
INFO: consulted 'foo.pl': 36 terms
DEBUG: orphaned=10
```

**Comment by infradig** [comment]
Can't reproduce:

$ cat samples/bar.pro
:- initialization(main).

foo(A, B) :- A = 1, write(B), nl.

main :- foo(X, X), halt.
andrew@andrew:~/trealla$ ./tpl samples/bar
Trealla v0.1alpha, 64-bits (int=128-bits), Feb 10 2017
INFO: consulted 'samples/bar': 36 terms
1
Halted
andrew@andrew:~/trealla$

**Comment by dram** [comment]
OK...

It is not related to unification. I leave an extra blank line before EOF, which is the cause.

```
% cat foo.pl
:- initialization(main).

foo(A, B) :- A = 1, write(B), nl.

main :- foo(X, X), halt.

% tpl --ns foo.pl
Trealla v0.1alpha, 64-bits (int=128-bits), Feb 10 2017
INFO: consulted 'foo.pl': 36 terms
DEBUG: orphaned=10
```

**Comment by infradig** [comment]
So how do you reproduce it? I tried 0, 1, 2+ blank lines...

**Comment by dram** [comment]
Sorry, please add one or more whitespaces in the last blank lines and try again.

**Comment by dram** [comment]
Add a test case in trealla-tests repo, hope that helps.

**Comment by infradig** [comment]
Ok, my editor settings strips trailing whitespace. I see now, and fixed.

**Comment by dram** [comment]
Thanks, fix confirmed.
