### ISSUE TITLE
How to use `sys:xmlq/3` to parse multiple entries 

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#98]
For following XML sample:

```
<?xml version="1.0"?>
<cities>
  <city>
    <name>City1</name>
    <country>Country1</country>
  </city>
  <city>
    <name>City2</name>
    <country>Country2</country>
  </city>
</cities>
```

Query using `sys:xmlq/3` will only get a single result:

```
?- sys:load_file('sample.xml', Xml), sys:xmlq(Xml, city, City).
```

**Comment by infradig** [comment]
You can use sys:xmlqi/4 to iterate over an index. Though to be honest sys:xmlq/3 should probably be retryable (?). I think i'll mark that as an enhancement.

**Comment by dram** [comment]
Yeah, I think it's reasonable to make it retryable.

**Comment by dram** [comment]
BTW, when trying to run `sys:xmlq(Xml, city, 1, City)`, Trealla report an `ABORT_INVALIDARGS` error.

**Comment by infradig** [comment]
>> BTW, when trying to run sys:xmlq(Xml, city, 1, City), Trealla report an ABORT_INVALIDARGS error.

I'll assume that was meant to be xmlqi/4. It might be an idea to remove that.

**Comment by dram** [comment]
Ah, I misread it, now both `xmlq/3` and `xmlqi/4` works.

BTW, REPL seems do not behave correctly for multiple values, I'll open another issue.
